"""renamed column email to email_address

Revision ID: d317268970be
Revises: 9abfc52b6ce7
Create Date: 2026-04-08 07:49:48.495467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd317268970be'
down_revision: Union[str, Sequence[str], None] = '9abfc52b6ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as op_batch:
        op_batch.alter_column('email',new_column_name = 'email_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as op_batch:
        op_batch.alter_column('email_address', new_column_name = 'email')
    # ### end Alembic commands ###
